# Generated by Django 5.2 on 2025-05-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint_app', '0002_alter_usergame_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='user',
        ),
    ]
