# Generated by Django 5.2 on 2025-05-05 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint_app', '0005_alter_usergame_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergame',
            unique_together={('user', 'game')},
        ),
    ]
