# Generated by Django 5.2 on 2025-05-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint_app', '0006_alter_usergame_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(default=1, max_length=20000),
            preserve_default=False,
        ),
    ]
