# Generated by Django 5.2 on 2025-05-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint_app', '0007_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(unique=True),
        ),
    ]
